 <?php
    // [
    //     'champion' => 'Afeganistão',
    //     'region' => 'Cabul'
    // ],


    return [
        ['champion' => 'Aatrox', 'region' => 'Runeterra'],
        ['champion' => 'Ahri', 'region' => 'Ionia'],
        ['champion' => 'Akali', 'region' => 'Ionia'],
        ['champion' => 'Alistar', 'region' => 'Runeterra'],
        ['champion' => 'Amumu', 'region' => 'Shurima'],
        ['champion' => 'Anivia', 'region' => 'Freljord'],
        ['champion' => 'Annie', 'region' => 'Noxus'],
        ['champion' => 'Aphelios', 'region' => 'Targon'],
        ['champion' => 'Ashe', 'region' => 'Freljord'],
        ['champion' => 'Aurelion Sol', 'region' => 'Targon'],
        ['champion' => 'Azir', 'region' => 'Shurima'],
        ['champion' => 'Bardo', 'region' => 'Runeterra'],
        ['champion' => 'BelVeth', 'region' => 'Vazio'],
        ['champion' => 'Blitzcrank', 'region' => 'Zaun'],
        ['champion' => 'Brand', 'region' => 'Freljord'],
        ['champion' => 'Braum', 'region' => 'Freljord'],
        ['champion' => 'Caitlyn', 'region' => 'Piltover'],
        ['champion' => 'Camille', 'region' => 'Piltover'],
        ['champion' => 'Cassiopeia', 'region' => 'Noxus'],
        ['champion' => 'ChoGath', 'region' => 'Vazio'],
        ['champion' => 'Corki', 'region' => 'Bandle'],
        ['champion' => 'Darius', 'region' => 'Noxus'],
        ['champion' => 'Diana', 'region' => 'Targon'],
        ['champion' => 'Dr.Mundo', 'region' => 'Zaun'],
        ['champion' => 'Draven', 'region' => 'Noxus'],
        ['champion' => 'Ekko', 'region' => 'Zaun'],
        ['champion' => 'Elise', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Evelynn', 'region' => 'Runeterra'],
        ['champion' => 'Ezreal', 'region' => 'Piltover'],
        ['champion' => 'Fiddlesticks', 'region' => 'Runeterra'],
        ['champion' => 'Fiora', 'region' => 'Demacia'],
        ['champion' => 'Fizz', 'region' => 'Águas de Sentina'],
        ['champion' => 'Galio', 'region' => 'Demacia'],
        ['champion' => 'Gangplank', 'region' => 'Águas de Sentina'],
        ['champion' => 'Garen', 'region' => 'Demacia'],
        ['champion' => 'Gnar', 'region' => 'Freljord'],
        ['champion' => 'Gragas', 'region' => 'Freljord'],
        ['champion' => 'Graves', 'region' => 'Águas de Sentina'],
        ['champion' => 'Gwen', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Hecarim', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Heimerdinger', 'region' => 'Piltover'],
        ['champion' => 'Illaoi', 'region' => 'Águas de Sentina'],
        ['champion' => 'Irelia', 'region' => 'Ionia'],
        ['champion' => 'Ivern', 'region' => 'Ionia'],
        ['champion' => 'Janna', 'region' => 'Zaun'],
        ['champion' => 'Jarvan IV', 'region' => 'Demacia'],
        ['champion' => 'Jax', 'region' => 'Runeterra'],
        ['champion' => 'Jayce', 'region' => 'Piltover'],
        ['champion' => 'Jhin', 'region' => 'Ionia'],
        ['champion' => 'Jinx', 'region' => 'Zaun'],
        ['champion' => 'KaiSa', 'region' => 'Vazio'],
        ['champion' => 'Kalista', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Karma', 'region' => 'Ionia'],
        ['champion' => 'Karthus', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Kassadin', 'region' => 'Vazio'],
        ['champion' => 'Katarina', 'region' => 'Noxus'],
        ['champion' => 'Kayle', 'region' => 'Demacia'],
        ['champion' => 'Kayn', 'region' => 'Noxus'],
        ['champion' => 'Kennen', 'region' => 'Ionia'],
        ['champion' => 'KhaZix', 'region' => 'Vazio'],
        ['champion' => 'Kindred', 'region' => 'Runeterra'],
        ['champion' => 'Kled', 'region' => 'Noxus'],
        ['champion' => 'KogMaw', 'region' => 'Vazio'],
        ['champion' => 'LeBlanc', 'region' => 'Noxus'],
        ['champion' => 'Lee Sin', 'region' => 'Ionia'],
        ['champion' => 'Leona', 'region' => 'Targon'],
        ['champion' => 'Lillia', 'region' => 'Ionia'],
        ['champion' => 'Lissandra', 'region' => 'Freljord'],
        ['champion' => 'Lucian', 'region' => 'Demacia'],
        ['champion' => 'Lulu', 'region' => 'Bandle'],
        ['champion' => 'Lux', 'region' => 'Demacia'],
        ['champion' => 'Malphite', 'region' => 'Ixtal'],
        ['champion' => 'Malzahar', 'region' => 'Shurima'],
        ['champion' => 'Maokai', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Master Yi', 'region' => 'Ionia'],
        ['champion' => 'Miss Fortune', 'region' => 'Águas de Sentina'],
        ['champion' => 'Mordekaiser', 'region' => 'Noxus'],
        ['champion' => 'Morgana', 'region' => 'Demacia'],
        ['champion' => 'Nami', 'region' => 'Águas de Sentina'],
        ['champion' => 'Nasus', 'region' => 'Shurima'],
        ['champion' => 'Nautilus', 'region' => 'Águas de Sentina'],
        ['champion' => 'Neeko', 'region' => 'Ixtal'],
        ['champion' => 'Nidalee', 'region' => 'Ixtal'],
        ['champion' => 'Nilah', 'region' => 'Águas de Sentina'],
        ['champion' => 'Nocturne', 'region' => 'Runeterra'],
        ['champion' => 'Nunu & Willump', 'region' => 'Freljord'],
        ['champion' => 'Olaf', 'region' => 'Freljord'],
        ['champion' => 'Orianna', 'region' => 'Piltover'],
        ['champion' => 'Ornn', 'region' => 'Freljord'],
        ['champion' => 'Pantheon', 'region' => 'Targon'],
        ['champion' => 'Poppy', 'region' => 'Demacia'],
        ['champion' => 'Pyke', 'region' => 'Águas de Sentina'],
        ['champion' => 'Qiyana', 'region' => 'Ixtal'],
        ['champion' => 'Quinn', 'region' => 'Demacia'],
        ['champion' => 'Rakan', 'region' => 'Ionia'],
        ['champion' => 'Rammus', 'region' => 'Shurima'],
        ['champion' => 'RekSai', 'region' => 'Vazio'],
        ['champion' => 'Rell', 'region' => 'Noxus'],
        ['champion' => 'Renata Glasc', 'region' => 'Zaun'],
        ['champion' => 'Renekton', 'region' => 'Shurima'],
        ['champion' => 'Rengar', 'region' => 'Ixtal']
    ];
    