 <?php
    // [
    //     'champion' => 'Afeganistão',
    //     'region' => 'Cabul'
    // ],

    return [
        ['champion' => 'Aatrox', 'region' => 'Runeterra'],
        ['champion' => 'Ahri', 'region' => 'Ionia'],
        ['champion' => 'Akali', 'region' => 'Ionia'],
        ['champion' => 'Alistar', 'region' => 'Runeterra'],
        ['champion' => 'Ambessa', 'region' => 'Noxus'],
        ['champion' => 'Amumu', 'region' => 'Shurima'],
        ['champion' => 'Anivia', 'region' => 'Freljord'],
        ['champion' => 'Annie', 'region' => 'Noxus'],
        ['champion' => 'Aphelios', 'region' => 'Targon'],
        ['champion' => 'Ashe', 'region' => 'Freljord'],
        ['champion' => 'Aurelion Sol', 'region' => 'Targon'],
        ['champion' => 'Aurora', 'region' => 'Freljord'],
        ['champion' => 'Azir', 'region' => 'Shurima'],
        ['champion' => 'Bardo', 'region' => 'Runeterra'],
        ['champion' => 'BelVeth', 'region' => 'Vazio'],
        ['champion' => 'Blitzcrank', 'region' => 'Zaun'],
        ['champion' => 'Brand', 'region' => 'Freljord'],
        ['champion' => 'Braum', 'region' => 'Freljord'],
        ['champion' => 'Briar', 'region' => 'Noxus'],
        ['champion' => 'Caitlyn', 'region' => 'Piltover'],
        ['champion' => 'Camille', 'region' => 'Piltover'],
        ['champion' => 'Cassiopeia', 'region' => 'Noxus'],
        ['champion' => 'ChoGath', 'region' => 'Vazio'],
        ['champion' => 'Corki', 'region' => 'Bandle'],
        ['champion' => 'Darius', 'region' => 'Noxus'],
        ['champion' => 'Diana', 'region' => 'Targon'],
        ['champion' => 'Dr.Mundo', 'region' => 'Zaun'],
        ['champion' => 'Draven', 'region' => 'Noxus'],
        ['champion' => 'Ekko', 'region' => 'Zaun'],
        ['champion' => 'Elise', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Evelynn', 'region' => 'Runeterra'],
        ['champion' => 'Ezreal', 'region' => 'Piltover'],
        ['champion' => 'Fiddlesticks', 'region' => 'Runeterra'],
        ['champion' => 'Fiora', 'region' => 'Demacia'],
        ['champion' => 'Fizz', 'region' => 'Águas de Sentina'],
        ['champion' => 'Galio', 'region' => 'Demacia'],
        ['champion' => 'Gangplank', 'region' => 'Águas de Sentina'],
        ['champion' => 'Garen', 'region' => 'Demacia'],
        ['champion' => 'Gnar', 'region' => 'Freljord'],
        ['champion' => 'Gragas', 'region' => 'Freljord'],
        ['champion' => 'Graves', 'region' => 'Águas de Sentina'],
        ['champion' => 'Gwen', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Hecarim', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Heimerdinger', 'region' => 'Piltover'],
        ['champion' => 'Hwei', 'region' => 'Ionia'],
        ['champion' => 'Illaoi', 'region' => 'Águas de Sentina'],
        ['champion' => 'Irelia', 'region' => 'Ionia'],
        ['champion' => 'Ivern', 'region' => 'Ionia'],
        ['champion' => 'Janna', 'region' => 'Zaun'],
        ['champion' => 'Jarvan IV', 'region' => 'Demacia'],
        ['champion' => 'Jax', 'region' => 'Runeterra'],
        ['champion' => 'Jayce', 'region' => 'Piltover'],
        ['champion' => 'Jhin', 'region' => 'Ionia'],
        ['champion' => 'Jinx', 'region' => 'Zaun'],
        ['champion' => 'KaiSa', 'region' => 'Vazio'],
        ['champion' => 'Kalista', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Karma', 'region' => 'Ionia'],
        ['champion' => 'Karthus', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Kassadin', 'region' => 'Vazio'],
        ['champion' => 'Katarina', 'region' => 'Noxus'],
        ['champion' => 'Kayle', 'region' => 'Demacia'],
        ['champion' => 'Kayn', 'region' => 'Noxus'],
        ['champion' => 'Kennen', 'region' => 'Ionia'],
        ['champion' => 'KhaZix', 'region' => 'Vazio'],
        ['champion' => 'Kindred', 'region' => 'Runeterra'],
        ['champion' => 'Kled', 'region' => 'Noxus'],
        ['champion' => 'KogMaw', 'region' => 'Vazio'],
        ['champion' => 'KSante', 'region' => 'Shurima'],
        ['champion' => 'LeBlanc', 'region' => 'Noxus'],
        ['champion' => 'Lee Sin', 'region' => 'Ionia'],
        ['champion' => 'Leona', 'region' => 'Targon'],
        ['champion' => 'Lillia', 'region' => 'Ionia'],
        ['champion' => 'Lissandra', 'region' => 'Freljord'],
        ['champion' => 'Lucian', 'region' => 'Demacia'],
        ['champion' => 'Lulu', 'region' => 'Bandle'],
        ['champion' => 'Lux', 'region' => 'Demacia'],
        ['champion' => 'Malphite', 'region' => 'Ixtal'],
        ['champion' => 'Malzahar', 'region' => 'Shurima'],
        ['champion' => 'Maokai', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Master Yi', 'region' => 'Ionia'],
        ['champion' => 'Milio', 'region' => 'Ixtal'],
        ['champion' => 'Miss Fortune', 'region' => 'Águas de Sentina'],
        ['champion' => 'Mordekaiser', 'region' => 'Noxus'],
        ['champion' => 'Morgana', 'region' => 'Demacia'],
        ['champion' => 'Naafiri', 'region' => 'Shurima'],
        ['champion' => 'Nami', 'region' => 'Águas de Sentina'],
        ['champion' => 'Nasus', 'region' => 'Shurima'],
        ['champion' => 'Nautilus', 'region' => 'Águas de Sentina'],
        ['champion' => 'Neeko', 'region' => 'Ixtal'],
        ['champion' => 'Nidalee', 'region' => 'Ixtal'],
        ['champion' => 'Nilah', 'region' => 'Águas de Sentina'],
        ['champion' => 'Nocturne', 'region' => 'Runeterra'],
        ['champion' => 'Nunu & Willump', 'region' => 'Freljord'],
        ['champion' => 'Olaf', 'region' => 'Freljord'],
        ['champion' => 'Orianna', 'region' => 'Piltover'],
        ['champion' => 'Ornn', 'region' => 'Freljord'],
        ['champion' => 'Pantheon', 'region' => 'Targon'],
        ['champion' => 'Poppy', 'region' => 'Demacia'],
        ['champion' => 'Pyke', 'region' => 'Águas de Sentina'],
        ['champion' => 'Qiyana', 'region' => 'Ixtal'],
        ['champion' => 'Quinn', 'region' => 'Demacia'],
        ['champion' => 'Rakan', 'region' => 'Ionia'],
        ['champion' => 'Rammus', 'region' => 'Shurima'],
        ['champion' => 'RekSai', 'region' => 'Vazio'],
        ['champion' => 'Rell', 'region' => 'Noxus'],
        ['champion' => 'Renata Glasc', 'region' => 'Zaun'],
        ['champion' => 'Renekton', 'region' => 'Shurima'],
        ['champion' => 'Rengar', 'region' => 'Ixtal'],
        ['champion' => 'Riven', 'region' => 'Noxus'],
        ['champion' => 'Rumble', 'region' => 'Bandle'],
        ['champion' => 'Ryze', 'region' => 'Runeterra'],
        ['champion' => 'Samira', 'region' => 'Noxus'],
        ['champion' => 'Sejuani', 'region' => 'Freljord'],
        ['champion' => 'Senna', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Seraphine', 'region' => 'Piltover'],
        ['champion' => 'Sett', 'region' => 'Ionia'],
        ['champion' => 'Shaco', 'region' => 'Runeterra'],
        ['champion' => 'Shen', 'region' => 'Ionia'],
        ['champion' => 'Shyvana', 'region' => 'Demacia'],
        ['champion' => 'Singed', 'region' => 'Zaun'],
        ['champion' => 'Sion', 'region' => 'Noxus'],
        ['champion' => 'Sivir', 'region' => 'Shurima'],
        ['champion' => 'Skarner', 'region' => 'Ixtal'],
        ['champion' => 'Smolder', 'region' => 'Camavor'],
        ['champion' => 'Sona', 'region' => 'Demacia'],
        ['champion' => 'Soraka', 'region' => 'Targon'],
        ['champion' => 'Swain', 'region' => 'Noxus'],
        ['champion' => 'Sylas', 'region' => 'Demacia'],
        ['champion' => 'Syndra', 'region' => 'Ionia'],
        ['champion' => 'Tahm Kench', 'region' => 'Águas de Sentina'],
        ['champion' => 'Taliyah', 'region' => 'Shurima'],
        ['champion' => 'Talon', 'region' => 'Noxus'],
        ['champion' => 'Taric', 'region' => 'Targon'],
        ['champion' => 'Teemo', 'region' => 'Bandle'],
        ['champion' => 'Thresh', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Tristana', 'region' => 'Bandle'],
        ['champion' => 'Trundle', 'region' => 'Freljord'],
        ['champion' => 'Tryndamere', 'region' => 'Freljord'],
        ['champion' => 'Twisted Fate', 'region' => 'Águas de Sentina'],
        ['champion' => 'Twitch', 'region' => 'Zaun'],
        ['champion' => 'Udyr', 'region' => 'Freljord'],
        ['champion' => 'Urgot', 'region' => 'Zaun'],
        ['champion' => 'Varus', 'region' => 'Ionia'],
        ['champion' => 'Vayne', 'region' => 'Demacia'],
        ['champion' => 'Veigar', 'region' => 'Bandle'],
        ['champion' => 'VelKoz', 'region' => 'Vazio'],
        ['champion' => 'Vex', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Vi', 'region' => 'Piltover'],
        ['champion' => 'Viego', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Viktor', 'region' => 'Zaun'],
        ['champion' => 'Vladimir', 'region' => 'Noxus'],
        ['champion' => 'Volibear', 'region' => 'Freljord'],
        ['champion' => 'Warwick', 'region' => 'Zaun'],
        ['champion' => 'Wukong', 'region' => 'Ionia'],
        ['champion' => 'Xayah', 'region' => 'Ionia'],
        ['champion' => 'Xerath', 'region' => 'Shurima'],
        ['champion' => 'Xin Zhao', 'region' => 'Demacia'],
        ['champion' => 'Yasuo', 'region' => 'Ionia'],
        ['champion' => 'Yone', 'region' => 'Ionia'],
        ['champion' => 'Yorick', 'region' => 'Ilhas das Sombras'],
        ['champion' => 'Yuumi', 'region' => 'Bandle'],
        ['champion' => 'Zac', 'region' => 'Zaun'],
        ['champion' => 'Zed', 'region' => 'Ionia'],
        ['champion' => 'Zeri', 'region' => 'Zaun'],
        ['champion' => 'Ziggs', 'region' => 'Zaun'],
        ['champion' => 'Zilean', 'region' => 'Runeterra'],
        ['champion' => 'Zoe', 'region' => 'Targon'],
        ['champion' => 'Zyra', 'region' => 'Ixtal'],
    ];
    